version: "3"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_USER_HOST: "%"
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: pokedex
    volumes:
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pokedex
    volumes:
      - ./scripts/postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: pokedex
    volumes:
      - ./scripts/mongodb-init.sh:/init-replica.sh
    command: /init-replica.sh
    ports:
      - 27017:27017
  redis:
    image: redis:7
    ports:
      - 6379:6379
  dockerize:
    image: jwilder/dockerize:latest
    depends_on:
      - mysql
      - postgres
      - mongodb
      - redis
    command: |
      dockerize
      -wait tcp://mysql:3306
      -wait tcp://postgres:5432
      -wait tcp://mongodb:27017
      -wait tcp://reids:6379
      -timeout 30s
  app:
    build: .
    environment:
      - DATABASE_URI
    ports:
      - 8000:8000
