version: '3'
services:
  app:
    image: app
    build: .
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    environment:
      SQLALCHEMY_DATABASE_URI: mysql+asyncmy://user:password@db:3306/pokedex
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: pokedex
    command: --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    ports:
      - 3366:3306
    expose:
      - 3366

